flags: {}
# setup-info:
#   ghc:
#     linux64-nopie:
#       8.2.0.20170507:
#         url: https://downloads.haskell.org/~ghc/8.2.1-rc2/ghc-8.2.0.20170507-x86_64-deb8-linux.tar.xz
#         sha1: ff886437c1d2ddfa5686d6c9efb0819a957c3dde
#         content-length: 141011788
#     linux64:
#       8.2.0.20170507:
#         url: https://downloads.haskell.org/~ghc/8.2.1-rc2/ghc-8.2.0.20170507-x86_64-deb8-linux.tar.xz
#         sha1: ff886437c1d2ddfa5686d6c9efb0819a957c3dde
#         content-length: 141011788

extra-deps:
  - QuickCheck-2.9.2
  - hashable-1.2.6.0
  - text-1.2.2.1
  - thrift-0.10.0
  - unordered-containers-0.2.8.0
  - vector-0.12.0.1
  - HTTP-4000.3.6
  - attoparsec-0.13.1.0
  - base64-bytestring-1.0.0.1
  - network-2.6.3.1
  - network-uri-2.6.1.0
  - primitive-0.6.2.0
  - random-1.1
  - split-0.2.3.2
  - tf-random-0.5
  - mtl-2.2.1
  - scientific-0.3.4.12
  - integer-logarithms-1.0.1
  - megaparsec-5.3.0
  - exceptions-0.8.3
  - stm-2.4.4.1
  - transformers-compat-0.5.1.4
  - optparse-applicative-0.13.2.0
  - ansi-wl-pprint-0.6.7.3
  - ansi-terminal-0.6.2.3
  - tar-0.5.0.3
  - zlib-0.6.1.2
  - filepath-1.4.1.2
  - process-1.6.0.0
  - directory-1.3.1.1
  - uuid-1.3.13
  - cryptohash-md5-0.11.100.1
  - cryptohash-sha1-0.11.100.1
  - entropy-0.3.7
  - network-info-0.2.0.8
  - uuid-types-1.0.3
  - Cabal-1.24.2.0

#compiler-check: match-exact
#compiler: ghc-8.2.0.20170507
#resolver: ghc-8.2.0.20170507
resolver: lts-8.15
allow-newer: true