flags:
  semigroups:
    bytestring-builder: false
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- '.'
system-ghc: true
extra-deps:
- HTTP-4000.3.3
- QuickCheck-2.8.1
- aeson-1.0.2.1
- attoparsec-0.13.1.0
- base-compat-0.9.1
- megaparsec-5.1.2
- network-uri-2.6.1.0
- semigroups-0.18.2
- split-0.2.3.1
- thrift-0.9.3
- time-locale-compat-0.1.1.3
- unordered-containers-0.2.5.1
resolver: ghc-7.10.3
