flags:
  generic-deriving:
    base-4-9: false
  semigroups:
    bytestring-builder: false
extra-package-dbs: []
packages:
- '.'
system-ghc: true
extra-deps:
- HTTP-4000.3.3
- QuickCheck-2.8.1
- adjunctions-4.3
- attoparsec-0.13.1.0
- bifunctors-5.2
- comonad-5
- contravariant-1.4
- free-4.12.4
- generic-deriving-1.11.1
- kan-extensions-5.0.1
- language-thrift-0.10.0.0
- lens-4.15.1
- megaparsec-5.1.2
- network-uri-2.6.1.0
- profunctors-5.2
- semigroupoids-5.0.1
- semigroups-0.18.2
- split-0.2.3.1
- thrift-0.9.3
- unordered-containers-0.2.5.1
- void-0.7.1
resolver: ghc-7.10.3
